#1. start multiple instance for high-availability
#2. must specifying git/svn repo url for fetch configuration
spring:
  application:
    name: config
  cloud:
    config:
      server:
        # git方式读取配置信息
        git:
#          basedir: D:\ideaprojectsa\git-config\basedir
          uri: https://gitee.com/fxcjj/config-repo
          username: 643117227@qq.com
          password: myiv901225
#          search-paths: /harpoon/base,/harpoon/common,/harpoon/gate,/harpoon/module
        # 本地方式读取配置信息
#        native:
#          search-locations: classpath:/base/,classpath:/common/,classpath:/gate/,classpath:/module/
# 将服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*" # 暴露所有端点
server:
  port: 8083