env:
  dev1aaaaa
zuul:
  # 配置超时
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
#  # 配置自定义路由
#  routes:
#    # 第一种写法 /myProduct/product/list -> /product/product/list
#    aaa:
#      path: /myProduct/**
#      serviceId: product
      # 针对此应用设置不过滤敏感头（默认过滤Cookie, Set-Cookie, Authorization），即应用接收所有头
      # sensitiveHeaders:
    # 第二种简洁写法
#    product: /myProduct/**
  # 禁止不需要暴露的路由,排除某些路由
#  ignored-patterns:
#    - /product/product/listForOrder
#    - /myProduct/product/listForOrder
    # 可使用通配符代替上面两个url
#    - /**/product/listForOrder
  # 全局敏感头,所有服务都可传递cookie，即不过滤请求headers，这样在路由到其它服务时，cookies才会传递过去
#  sensitive-headers: