server:
  port: 8097
spring:
  application:
    name: admin
# \u5C06\u670D\u52A1\u6CE8\u518C\u5230eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# \u7AEF\u70B9\u7BA1\u7406
management:
  endpoints.sen:
    web:
      exposure:
        # \u66B4\u9732\u6240\u6709\u7AEF\u70B9
        include: "*"
