eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
#  instance:
#      hostname: hostname-eureka02
spring:
  application:
    name: eureka02
server:
  port: 8762