spring:
  #JPA配置
  jpa:
    database: mysql
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
#    hibernate:
#      ddl-auto: update
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_sell?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #platform: mysql
    #type: com.alibaba.druid.pool.DruidDataSource
    # -----------------初始化大小，最小，最大----------------------------
    hikari:
      # 连接只读数据库时配置为true，保证安全
      # read-only: true
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 60000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 128
      minimum-idle: 24
      pool-name: HikariPool
      register-mbeans: true