spring:
  # zipkin链路追踪
  zipkin:
    base-url: http://192.168.6.131:9411
    # Enables sending spans to zipkin
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true