eureka:
  client:
    service-url:
      #register ip to eureka
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    hostname: localhost #custom redirect ip
spring:
  application:
    name: client
server:
  port: 8081