eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
#  instance:
#    hostname: hostname-eureka03
#    prefer-ip-address: true
spring:
  application:
    name: eureka03
server:
  port: 8763