server:
  port: 8763

spring:
  application:
    name: eureka03

eureka:
  # 当前eureka实例相关配置
  instance:
    # eureka实例主机名
    hostname: peer3
    # 注册到eureka中的唯一标记，目前作用仅是显示
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}

    # 集群中各服务之间互相访问默认使用hostname进行，但是这样需要在各个机器上配置hosts文件。将该配置设为true，可以尽量使用ip进行通信
    prefer-ip-address: false
  # 当前eureka client端相关配置
  client:
    # 注册中心地址
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8763/eureka/

  # 当前eureka server端相关配置
  server:
    enable-self-preservation: false

